version: "3.12"

services:
  db:
    image: postgres:15
    container_name: openinfraetl_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: jay
      POSTGRES_PASSWORD: password
      POSTGRES_DB: openinfraetl
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
